name: Build GH Pages

on:
  push:
    branches: ['master']
    # paths: ['build/*.json', 'build/build.php', 'build/extensions/*.php', 'build/*.txt']

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Run the build php script
    #   run: |
    #     cd build
    #     php build.php  
    #     cd ../
    - name: Commit files  
      run: |
        git config --local user.name  ${{ github.actor }}
        git add ./docs
        git commit -m "Updating the repository GitHub html pages in the docs folder"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
