name: Simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trying_to_start_apache_server_and_access_file_from_it:
   runs-on: ubuntu-latest
   steps:        
    - uses: actions/checkout@v3
    - run: |
        RUNNER_TRACKING_ID=""
        sudo apt install apache2
        sudo apt install nodejs
        node -v
        npm install pm2 -g
        sudo service apache2 restart
        pm2 start script.js
        hostname -i
