name: Simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  writing_secrets_to_file:
   runs-on: ubuntu-latest
   steps:
    - run: sudo apt install nodejs
    - run: node -v

